### ISSUE TITLE
Discord issues

### ISSUE THREAD

**Issue by Aturok87** [bhigginsuk/discord-activity-monitor#36]
so i have been hosting the bot for 2 years since the project ended and i plan on modifying and adding features here and there to the bot and waiting to make the bot stable to add the features and then this started happening since discord added the slash command update and now this keeps happening 

[1924] [Sun, 18 Apr 2021 01:41:30 GMT] [INFO] Using database protocol nedb://
[1924] [Sun, 18 Apr 2021 01:41:33 GMT] [ERROR] Unhandled exception! | Cannot read property 'id' of undefined
[1924] [Sun, 18 Apr 2021 01:41:33 GMT] [INFO] Shutdown with code 100

how do i fix this?

**Comment by Aturok87** [comment]
sorted it out figured out the right settings and converted them

**Comment by Aturok87** [comment]
(node:19908) UnhandledPromiseRejectionWarning: TypeError: member.djs.roles.has is not a function
    at D:\bot\discord-activity-monitor-master\dist\models\guild.js:26:84
    at Array.some (<anonymous>)
    at Guild.isMemberIgnored (D:\bot\discord-activity-monitor-master\dist\models\guild.js:26:52)
    at ActivityRegisterer.registerActivity (D:\bot\discord-activity-monitor-master\dist\core\activity-registerer.js:23:22)

**Comment by Aturok87** [comment]
working on fixing the frame work for the bot 
to resolve this issue

**Comment by verwischt** [comment]
Hello Aturo, can you explain what settings I have to change for make this work?

**Comment by Aturok87** [comment]
its not settings the entire bot had to be reprogramed entirly i have reprogramed it and are making some modifcatons to add new roles like dead and a auto kick function to the bot along with a reinvite back to the server that can be customized if its something your interested in using let me know its on top.gg right now its down as i will be adding a few things to it

**Comment by Aturok87** [comment]
just look up activity monitor V4
